/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemarlf.visualizacao.ordemprod;

import java.util.List;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import sistemarlf.modelo.entidades.ordem.OrdemProducao;
import sistemarlf.modelo.entidades.pedido.Pedido;
import sistemarlf.modelo.oad.ordem.OADOrdemProducao;
import sistemarlf.modelo.oad.pedido.OADPedido;

/**
 *
 * @author Rosaine e Jhonnatan
 */
public class FormConsultaOrdemProd extends javax.swing.JPanel {
    JInternalFrame telaCarregada;
    DefaultTableModel tmConsultaOrdemProd;
    /**
     * Creates new form ProtCadastraCliente
     */
    public FormConsultaOrdemProd(JInternalFrame jfCarregada) {
        initComponents();
        telaCarregada = jfCarregada;
        consultarOrdens(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtCodProduto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDataPedido = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gridConsulta = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        btnSelecionar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setAutoscrolls(true);
        setMaximumSize(new java.awt.Dimension(0, 0));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setName("ProtCadastraCliente"); // NOI18N
        setPreferredSize(new java.awt.Dimension(700, 500));
        setVerifyInputWhenFocusTarget(false);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("sistemarlf/visualizacao/produto/Bundle"); // NOI18N
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("FormConsultaProduto.jPanel1.border.title"))); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(750, 400));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 300));

        jLabel4.setText(bundle.getString("FormConsultaProduto.jLabel4.text")); // NOI18N

        txtCodProduto.setText(bundle.getString("FormConsultaProduto.txtCodProdPedido.text")); // NOI18N
        txtCodProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodProdutoKeyReleased(evt);
            }
        });

        jLabel10.setText(bundle.getString("FormConsultaProduto.jLabel10.text")); // NOI18N

        txtDataPedido.setText(bundle.getString("FormConsultaProduto.txtDescProdPedido.text")); // NOI18N

        btnPesquisar.setText(bundle.getString("FormConsultaProduto.btnPesqProd.text")); // NOI18N
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(4, 4, 4)
                .addComponent(txtCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDataPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(btnPesquisar))
                    .addComponent(txtCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new java.awt.BorderLayout());

        gridConsulta.setAutoCreateRowSorter(true);
        tmConsultaOrdemProd = new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód.Ordem", "Cód.Produto", "Descrição Produto", "Qtde Itens", "Situação", "Data Emissão"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.util.Date.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
        gridConsulta.setModel(tmConsultaOrdemProd);
        gridConsulta.setAutoscrolls(false);
        gridConsulta.setEditingRow(0);
        gridConsulta.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        gridConsulta.getTableHeader().setReorderingAllowed(false);
        gridConsulta.setCellSelectionEnabled(false);
        gridConsulta.setRowSelectionAllowed(true);
        gridConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gridConsultaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(gridConsulta);
        gridConsulta.getColumnModel().getColumn(0).setPreferredWidth(20);
        gridConsulta.getColumnModel().getColumn(1).setPreferredWidth(20);
        gridConsulta.getColumnModel().getColumn(2).setPreferredWidth(100);
        gridConsulta.getColumnModel().getColumn(3).setPreferredWidth(20);
        gridConsulta.getColumnModel().getColumn(4).setPreferredWidth(20);
        gridConsulta.getColumnModel().getColumn(5).setPreferredWidth(20);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btnSelecionar.setText(bundle.getString("FormConsultaProduto.btnFechar.text")); // NOI18N
        btnSelecionar.setFocusable(false);
        btnSelecionar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSelecionar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });

        btnExcluir.setText(bundle.getString("FormConsultaProduto.btnExcluir.text")); // NOI18N
        btnExcluir.setFocusable(false);
        btnExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
                            .addComponent(jSeparator1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSelecionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSelecionar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName(bundle.getString("FormConsultaProduto.AccessibleContext.accessibleName")); // NOI18N
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
            telaCarregada.dispose();
    }//GEN-LAST:event_btnSelecionarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
    OrdemProducao op = new OrdemProducao();
    op.setCodigo((Integer) tmConsultaOrdemProd.getValueAt(gridConsulta.getSelectedRow(), 0));
    op = new OADOrdemProducao().CarregaComItens(op);
    try{        
        for (int i = 0; i < op.getItens().size(); i++){
            op.getItens().get(i).setSituacao('1');
        }
       // situação = CANCELADA
        op.setSituacao('4');
        new OADOrdemProducao().salvar(op);

        for (int i = 0; i < op.getItens().size(); i++){
            op.getItens().get(i).setSituacao('1');
            Pedido pedido = new Pedido();
            pedido.setCodigo(op.getItens().get(i).getPedido().getCodigo());
            pedido = new OADPedido().carrega(pedido);
            if (pedido.getSituacao().equals('3')){
                pedido.setSituacao('2');
                new OADPedido().salvar(pedido);
            }            
        }
        
//        pedidosComProduto = new OADItem().ListaPedidosComProduto(produtoSelecionado);
//        for (int i = 0; i < pedidosComProduto.size(); i++){
//            listaItensEmCadastramentoPedido = new OADItem().ListaPeloPedido(pedidosComProduto.get(i));
//            if ((listaItensEmCadastramentoPedido == null) || (listaItensEmCadastramentoPedido.isEmpty())){
//                fecharPedido(pedidosComProduto.get(i));
//            }
//        }
//            Pedido pedido = new Pedido();
//            pedido.setCodigo(op.getItens().get(i).getPedido().getCodigo());
//            pedido = new OADPedido().carrega(pedido);
//            if (pedido.getSituacao().equals('3')){
//                pedido.setSituacao('2');
//                new OADPedido().salvar(pedido);
//            }            

        
        
       // situação = CANCELADA
        op.setSituacao('4');
        new OADOrdemProducao().salvar(op);
        if(new OADOrdemProducao().salvar(op)){
            JOptionPane.showMessageDialog(this, "Ordem de Produção Cancelada com sucesso!", "", JOptionPane.INFORMATION_MESSAGE);        
            consultarOrdens(null);
            txtCodProduto.requestFocus();
        }else{
            JOptionPane.showMessageDialog(this, "Erro ao cancelar Ordem de Produção!", "", JOptionPane.ERROR_MESSAGE);        
        }
    }catch(Exception e){
        System.out.println(e.toString());
    }

        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        OrdemProducao pcons = new OrdemProducao();
        if (!txtCodProduto.getText().trim().isEmpty()){
            pcons.setCodigo(Integer.valueOf(txtCodProduto.getText()));
        }else
            pcons = null;
        consultarOrdens(pcons);
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void gridConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gridConsultaMouseClicked

    }//GEN-LAST:event_gridConsultaMouseClicked

    private void txtCodProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodProdutoKeyReleased
        JTextField t = (JTextField) evt.getSource();
        t.setText(t.getText().replaceAll("[^0-9]", ""));        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodProdutoKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton btnExcluir;
    javax.swing.JButton btnPesquisar;
    javax.swing.JButton btnSelecionar;
    javax.swing.JTable gridConsulta;
    javax.swing.JLabel jLabel10;
    javax.swing.JLabel jLabel4;
    javax.swing.JPanel jPanel1;
    javax.swing.JPanel jPanel2;
    javax.swing.JScrollPane jScrollPane1;
    javax.swing.JSeparator jSeparator1;
    javax.swing.JTextField txtCodProduto;
    javax.swing.JTextField txtDataPedido;
    // End of variables declaration//GEN-END:variables

    private void limparCampos() {
        txtCodProduto.setText(null);
        txtDataPedido.setText(null);
    }

    public void consultarOrdens(OrdemProducao p) {
        tmConsultaOrdemProd.setRowCount(0);
             
        if ((p == null) || ((p.getCodigo() == null || p.getCodigo().equals(0)))){
            List<OrdemProducao> lp = new OADOrdemProducao().CarregaTodosComItens();
            for (int i = 0; i < lp.size(); i++){
                tmConsultaOrdemProd.addRow(lp.get(i).getLinha());
            }
        }else{
            p = new OADOrdemProducao().carrega(p);
            tmConsultaOrdemProd.addRow(p.getLinha());
        }
            
            
    }


}
