/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Prototipo;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Wine
 */
public class ProtCadastraPedido extends javax.swing.JPanel {

    JFrame telaChamadora;
    DefaultTableModel tmProdtPedido;

    /**
     * Creates new form ProtCadastraCliente
     */
    public ProtCadastraPedido(JFrame jfChamador) {
        initComponents();
        tmProdtPedido = new DefaultTableModel(new Object [][] {

            },
            new String [] {
                "Cód Prod", "Desc Prod", "Tamanho", "Cor", "Qtde", "Vlr Unit", "Vlr Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
        gridProdPedido.setModel(tmProdtPedido);
        gridProdPedido.setAutoscrolls(false);
        gridProdPedido.setColumnSelectionAllowed(true);
        gridProdPedido.setEditingRow(0);
        gridProdPedido.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        gridProdPedido.getTableHeader().setReorderingAllowed(false);
        gridProdPedido.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        gridProdPedido.getColumnModel().getColumn(0).setPreferredWidth(20);
        gridProdPedido.getColumnModel().getColumn(1).setPreferredWidth(300);
        gridProdPedido.getColumnModel().getColumn(2).setPreferredWidth(20);
        gridProdPedido.getColumnModel().getColumn(3).setPreferredWidth(20);
        gridProdPedido.getColumnModel().getColumn(4).setPreferredWidth(20);
        gridProdPedido.getColumnModel().getColumn(5).setPreferredWidth(20);
        gridProdPedido.getColumnModel().getColumn(6).setPreferredWidth(20);
        gridProdPedido.setCellSelectionEnabled(false);
        gridProdPedido.setRowSelectionAllowed(true);
        
        telaChamadora = jfChamador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtCodPedido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDataInclPedido = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtCodProdPedido = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDescProdPedido = new javax.swing.JTextField();
        btnPesqProd = new javax.swing.JButton();
        cmbTamProdPedido = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbCorProdPedido = new javax.swing.JComboBox();
        btnNovoTamProdPedido = new javax.swing.JButton();
        btnNovaCorProdPedido = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnExcluirProdPedido = new javax.swing.JButton();
        btnIncluirProdPedido = new javax.swing.JButton();
        txtQtdeProdPedido = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gridProdPedido = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtVlrTotalPedido = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtVlrProdPedido = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnFechar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNomeClientePedido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCpfCnpjClientePedido = new javax.swing.JTextField();
        btnPesqCliente = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Pedidos"));
        setAutoscrolls(true);
        setMaximumSize(new java.awt.Dimension(0, 0));
        setName("ProtCadastraCliente"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 700));
        setVerifyInputWhenFocusTarget(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel3.setText("Código:");

        txtCodPedido.setEditable(false);
        txtCodPedido.setFocusable(false);

        jLabel2.setText("Data Inclusão:");

        txtDataInclPedido.setEditable(false);
        txtDataInclPedido.setFocusable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleção do Produto"));
        jPanel1.setMaximumSize(new java.awt.Dimension(750, 400));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 300));

        jLabel4.setText("Código Produto:");

        txtCodProdPedido.setText("1");

        jLabel10.setText("Descrição Produto:");

        txtDescProdPedido.setText("produto teste");

        btnPesqProd.setText("Pesquisar");

        cmbTamProdPedido.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "P", "M", "G", "GG", "EG", "EGG", "1", "2", "4", "6", "8", "10", "12", "14", "16", "34", "36", "38", "40", "42", "44", "46", "48", "50", "52", "54", "56" }));

        jLabel6.setText("Tamanho:");

        jLabel7.setText("Cor:");

        cmbCorProdPedido.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AZUL", "AMARELO", "VERDE", "VERMELHO", "PRETO", "BRANCO", "BRANCO/PRETO", "LISTRADO BRANCO/PRETO" }));

        btnNovoTamProdPedido.setText("+");

        btnNovaCorProdPedido.setText("+");

        btnExcluirProdPedido.setText("Excluir Produto");
        btnExcluirProdPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirProdPedidoActionPerformed(evt);
            }
        });

        btnIncluirProdPedido.setText("Incluir Produto");
        btnIncluirProdPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirProdPedidoActionPerformed(evt);
            }
        });

        txtQtdeProdPedido.setText("2");

        jLabel8.setText("Quantidade:");

        gridProdPedido.setAutoCreateRowSorter(true);
        gridProdPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód Prod", "Desc Prod", "Tamanho", "Cor", "Qtde", "Vlr Unit", "Vlr Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gridProdPedido.setAutoscrolls(false);
        gridProdPedido.setColumnSelectionAllowed(true);
        gridProdPedido.setEditingRow(0);
        gridProdPedido.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        gridProdPedido.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(gridProdPedido);
        gridProdPedido.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        gridProdPedido.getColumnModel().getColumn(0).setPreferredWidth(20);
        gridProdPedido.getColumnModel().getColumn(1).setPreferredWidth(300);
        gridProdPedido.getColumnModel().getColumn(2).setPreferredWidth(20);
        gridProdPedido.getColumnModel().getColumn(3).setPreferredWidth(20);
        gridProdPedido.getColumnModel().getColumn(4).setPreferredWidth(20);
        gridProdPedido.getColumnModel().getColumn(5).setPreferredWidth(20);
        gridProdPedido.getColumnModel().getColumn(6).setPreferredWidth(20);

        jLabel9.setText("Valor Total do Pedido:");

        txtVlrTotalPedido.setText("0.0");
        txtVlrTotalPedido.setEnabled(false);
        txtVlrTotalPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVlrTotalPedidoActionPerformed(evt);
            }
        });

        jLabel11.setText("Valor:");

        txtVlrProdPedido.setText("15.50");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVlrTotalPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(4, 4, 4)
                                .addComponent(txtCodProdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDescProdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesqProd))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel6)
                                        .addGap(4, 4, 4)
                                        .addComponent(cmbTamProdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtQtdeProdPedido)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(btnNovoTamProdPedido)
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel7)
                                        .addGap(4, 4, 4)
                                        .addComponent(cmbCorProdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(btnNovaCorProdPedido))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtVlrProdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnIncluirProdPedido)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnExcluirProdPedido))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 22, Short.MAX_VALUE))
                    .addComponent(jSeparator2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtCodProdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDescProdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPesqProd))))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbTamProdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovoTamProdPedido)
                    .addComponent(cmbCorProdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovaCorProdPedido)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtQtdeProdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVlrProdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluirProdPedido)
                    .addComponent(btnIncluirProdPedido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVlrTotalPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap())
        );

        jPanel3.setMaximumSize(new java.awt.Dimension(750, 50));
        jPanel3.setMinimumSize(new java.awt.Dimension(750, 50));
        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(750, 50));

        btnFechar.setText("Fechar");
        btnFechar.setFocusable(false);
        btnFechar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFechar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.setFocusable(false);
        btnSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(606, Short.MAX_VALUE)
                .addComponent(btnFechar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar)
                .addGap(16, 16, 16))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnFechar)
                    .addComponent(btnSalvar))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleção do Cliente"));

        jLabel1.setText("Cliente:");

        jLabel5.setText("CPF/CNPJ:");

        btnPesqCliente.setText("Pesquisar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(txtNomeClientePedido, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCpfCnpjClientePedido, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesqCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtNomeClientePedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCpfCnpjClientePedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPesqCliente)))
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(4, 4, 4)
                        .addComponent(txtCodPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(409, 409, 409)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataInclPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCodPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(txtDataInclPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        telaChamadora.dispose();


    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        JOptionPane.showMessageDialog(this, "Registro Salvo com sucesso!", "", JOptionPane.INFORMATION_MESSAGE);
        limparCampos();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
    }//GEN-LAST:event_formComponentShown

    private void btnExcluirProdPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirProdPedidoActionPerformed
        // TODO add your handling code here:
        ProtClassProdtPedido pp = new ProtClassProdtPedido();
        pp.setCodProdtPedido(Integer.valueOf(txtCodProdPedido.getText()));
        pp.setDescProdtPedido(txtDescProdPedido.getText());
        pp.setTamProdtPedido(String.valueOf(cmbTamProdPedido.getSelectedItem()));
        pp.setCorProdtPedido(String.valueOf(cmbCorProdPedido.getSelectedItem()));
        pp.setQtdeProdtPedido(Double.valueOf(txtQtdeProdPedido.getText()));
        pp.setVlrUnitProdtPedido(Double.valueOf(txtVlrProdPedido.getText()));
        tmProdtPedido.removeRow(gridProdPedido.getSelectedRow());
        atualizaValorPedido(false, pp.getVlrTotalProdtPedido());
    }//GEN-LAST:event_btnExcluirProdPedidoActionPerformed

    private void btnIncluirProdPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirProdPedidoActionPerformed
        // TODO add your handling code here:

        ProtClassProdtPedido pp = new ProtClassProdtPedido();

        pp.setCodProdtPedido(Integer.valueOf(txtCodProdPedido.getText()));
        pp.setDescProdtPedido(txtDescProdPedido.getText());
        pp.setTamProdtPedido(String.valueOf(cmbTamProdPedido.getSelectedItem()));
        pp.setCorProdtPedido(String.valueOf(cmbCorProdPedido.getSelectedItem()));
        pp.setQtdeProdtPedido(Double.valueOf(txtQtdeProdPedido.getText()));
        pp.setVlrUnitProdtPedido(Double.valueOf(txtVlrProdPedido.getText()));
        tmProdtPedido.addRow(pp.getLinha());
        atualizaValorPedido(true, pp.getVlrTotalProdtPedido());





    }//GEN-LAST:event_btnIncluirProdPedidoActionPerformed

    private void txtVlrTotalPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVlrTotalPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVlrTotalPedidoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton btnExcluirProdPedido;
    javax.swing.JButton btnFechar;
    javax.swing.JButton btnIncluirProdPedido;
    javax.swing.JButton btnNovaCorProdPedido;
    javax.swing.JButton btnNovoTamProdPedido;
    javax.swing.JButton btnPesqCliente;
    javax.swing.JButton btnPesqProd;
    javax.swing.JButton btnSalvar;
    javax.swing.JComboBox cmbCorProdPedido;
    javax.swing.JComboBox cmbTamProdPedido;
    javax.swing.JTable gridProdPedido;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel10;
    javax.swing.JLabel jLabel11;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel3;
    javax.swing.JLabel jLabel4;
    javax.swing.JLabel jLabel5;
    javax.swing.JLabel jLabel6;
    javax.swing.JLabel jLabel7;
    javax.swing.JLabel jLabel8;
    javax.swing.JLabel jLabel9;
    javax.swing.JPanel jPanel1;
    javax.swing.JPanel jPanel2;
    javax.swing.JPanel jPanel3;
    javax.swing.JScrollPane jScrollPane1;
    javax.swing.JSeparator jSeparator2;
    javax.swing.JTextField txtCodPedido;
    javax.swing.JTextField txtCodProdPedido;
    javax.swing.JTextField txtCpfCnpjClientePedido;
    javax.swing.JTextField txtDataInclPedido;
    javax.swing.JTextField txtDescProdPedido;
    javax.swing.JTextField txtNomeClientePedido;
    javax.swing.JTextField txtQtdeProdPedido;
    javax.swing.JTextField txtVlrProdPedido;
    javax.swing.JTextField txtVlrTotalPedido;
    // End of variables declaration//GEN-END:variables

    private void limparCampos() {
        txtNomeClientePedido.setText(null);
        txtDataInclPedido.setText(null);
        txtCodPedido.setText(null);
        txtCodProdPedido.setText(null);
        txtDescProdPedido.setText(null);
        txtVlrTotalPedido.setText("0");


    }

    private void atualizaValorPedido(boolean adicionar, double vlrProd) {
        if (adicionar)
            txtVlrTotalPedido.setText(String.valueOf(Double.valueOf(txtVlrTotalPedido.getText()) + vlrProd));
        else
            txtVlrTotalPedido.setText(String.valueOf(Double.valueOf(txtVlrTotalPedido.getText()) - vlrProd));
    }
}
